=== tidianesow/xml/projet_dss_chat/dtd/groups.dtd
<!ELEMENT groups (group+)>
<!ELEMENT group (name, members, admin)>
<!ATTLIST group id ID #REQUIRED>
<!ELEMENT name (#PCDATA)>
<!ELEMENT members (member+)>
<!ELEMENT member (#PCDATA)>
<!ELEMENT admin (#PCDATA)>

=== tidianesow/xml/projet_dss_chat/data/groups.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE groups SYSTEM "groups.dtd">
<groups>
<group id="g68744b44a2b21"><name>projetxml</name><members><member>u68740edb4bb55</member></members><admin>u68740edb4bb55</admin></group><group id="g68744d56f090f"><name>projet1</name><members><member>u68744d3596045</member></members><admin>u68744d3596045</admin></group><group id="g6874e83d8cd31"><name>groupe1</name><members><member>u68740edb4bb55</member></members><admin>u68740edb4bb55</admin></group></groups>
