=== tidianesow/xml/projet_dss_chat/dtd/messages.dtd
<!ELEMENT messages (message+)>
<!ELEMENT message (sender, receiver, content, timestamp, type)>
<!ATTLIST message id ID #REQUIRED>
<!ELEMENT sender (#PCDATA)>
<!ELEMENT receiver (#PCDATA)>
<!ATTLIST receiver type (user | group) #REQUIRED>
<!ELEMENT content (#PCDATA)>
<!ELEMENT timestamp (#PCDATA)>
<!ELEMENT type (text | file)>

=== tidianesow/xml/projet_dss_chat/data/messages.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE messages SYSTEM "messages.dtd">
<messages>
<message id="m68740ab554973"><sender>u68740a975f91a</sender><receiver type="user">12</receiver><content>salut</content><timestamp>2025-07-13T19:36:21+00:00</timestamp><type>text</type></message><message id="m687410fdaaac3"><sender>u68740edb4bb55</sender><receiver type="user">12</receiver><content>adcxcv</content><timestamp>2025-07-13T20:03:09+00:00</timestamp><type>text</type></message><message id="m687452ce597ae"><sender>u68740edb4bb55</sender><receiver type="user">12</receiver><content>slt</content><timestamp>2025-07-14T00:43:58+00:00</timestamp><type>text</type></message></messages>
