=== tidianesow/xml/projet_dss_chat/dtd/users.dtd
<!ELEMENT users (user+)>
<!ELEMENT user (username, password, email, status, last_login?)>
<!ATTLIST user id ID #REQUIRED>
<!ELEMENT username (#PCDATA)>
<!ELEMENT password (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT status (#PCDATA)>
<!ELEMENT last_login (#PCDATA)>

=== tidianesow/xml/projet_dss_chat/data/users.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE users SYSTEM "users.dtd">
<users>
<user id="u68740a975f91a"><username>tidiane</username><password>$2y$12$DQkZQWWAiBJ6NY9xPJuIIejxlQGh1MSABmBKfM1jMAuNc/LnpgOUO</password><email>sowtidiane39@gmail.com</email><status>offline</status><last_login>2025-07-13T19:36:07+00:00</last_login></user><user id="u68740edb4bb55"><username>tidiane2</username><password>$2y$12$elJkT.2ICKsJPaczdXD.Z.4Z95TewoZB3F3God.lKyR0VASt3YeJ2</password><email>sowtidiane3@gmail.com</email><status>offline</status><last_login>2025-07-14T11:51:10+00:00</last_login></user><user id="u68744d3596045"><username>cheikhona</username><password>$2y$12$HvZrIpVPsIC8ExoGBSNXy.F670aMGPQClNXJJY1ne9XilZVEAvBye</password><email>cheikhona12@gnm.com</email><status>online</status><last_login>2025-07-14T20:24:10+00:00</last_login></user></users>
